from fastapi import APIRouter, Depends
from pymongo.database import Database
from app.database import get_db
from app.services.complaint_manager import complaint_manager
from app.services.statistics_engine import statistics_engine

router = APIRouter()

@router.get("/")
def get_analytics(db: Database = Depends(get_db)):
    """
    Returns full statistical analytical metrics generated by StatisticsEngine.
    Includes Mean, Median, Mode, Min, Max, Range, Variance, Std Dev, IQR boxplot analysis,
    frequency distributions, and narrative insights.
    """
    complaints = complaint_manager.get_all(db, limit=2000)
    return statistics_engine.generate_full_analytics(complaints)
